config/routes.rb
Rails.application.routes.draw do
  resources :likes , :only => [:destroy]
  resources :pins do
    resources :likes , :only => [:create]
  end
  

root "pins#index"
get "about" => "pages#about"
devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :pin
  validates :user_id, presence: true
  validates :pin_id, presence: true
  validates_uniqueness_of :user_id, :scope => :pin_id
end

app/models/pin.rb
# -*- coding: utf-8 -*-
class Pin < ActiveRecord::Base
	belongs_to :user
	has_many :likes, :dependent => :destroy
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	# validates :image, presence: true
	# validates :description, presence: true
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  before_save :add_defaults
  default_scope {where("user_id is not null")}
  MESSAGES = ["Wish you a very happy birthday David!", "Many Many happy returns of the day David!", "Have a great Birthday David!", "Here’s to lots of celebration today! We wish you lots of good health for you and your loved ones in the coming year :)", "Remember this wise saying on your happy day: the more you celebrate your life, the more there is in life to celebrate!", "Have a wonderful happy, healthy birthday and many more to come. Happy Birthday!"]
  
  def add_defaults
    self.description = MESSAGES.sample if self.description.blank?
    self.image = open Pin.unscoped.where("user_id is null").to_a.sample.image(:medium)  if self.image.blank?
  end
  
  def self.create_defaults
    (1..32).to_a.each do |i|
      Pin.create
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are :lockable, :timeoutable and :omniauthable
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :name, presence: true
  has_many :identities, :dependent => :destroy
  has_many :pins, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  
  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
    if user.nil?
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email
      if user.nil?
        if auth.provider == 'twitter'
          user = self.generate_user_from_twitter(auth, email) 
        elsif auth.provider == 'facebook'
          user = self.generate_user_from_facebook(auth, email)  
        end
        user.save!
      end
    end
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end
  
  def self.generate_user_from_twitter(auth, email)
      user = User.new(name: auth.info.name,
        twitter_handle: auth.info.nickname,
        email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
        password: Devise.friendly_token[0,20],
        profile_picture: auth.info.image
      )
  end

  def self.generate_user_from_facebook(auth, email)
    sep = auth.info.image.include?('?') ? '&' : '?'
      user = User.new(name: auth.info.name,
        email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
        password: Devise.friendly_token[0,20],
        profile_picture: auth.info.image + "#{sep}width=1000"
      )
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  def twitter_handle_display
    twitter_handle ? "@#{twitter_handle}" : ""
  end
  
  def profile_pic_url
    return profile_picture if profile_picture.present?
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://www.gravatar.com/avatar/#{hash}?s=200" 
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!
  def create
    @like = current_user.likes.build(pin_id: params[:pin_id])
    @like.save
    @pin = Pin.find(params[:pin_id]);
#    render :template =>  "pins/_pin" ,:locals => {:pin => @pin}
    render :partial =>"pins/pin", :locals => {:pin => @pin}
  end

  def destroy
    pinId = Like.find(params[:id]).pin_id
    Like.find(params[:id]).destroy
    @pin = Pin.find(pinId)
    render :partial =>"pins/pin", :locals => {:pin => @pin}
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook].each do |provider|
    provides_callback_for provider
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :validate_pins_count, only: [:new, :create]
  before_action :list_all_pins, only: [:new, :index]
 
  def index
  
end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      @user = current_user;
      # UserMailer.thanks_email(@user).deliver
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pin_params
    params.require(:pin).permit(:description, :image)
  end
  
  #User can create only one pin
  def validate_pins_count
      if current_user.pins.count >= 1
        redirect_to pins_url, notice: 'You can create only one pin.'
      end
  end
  
  #to get all pins
  def list_all_pins
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<%- digits_array = Pin.count.to_s.chars.to_a.reverse%>
<p class="hidden" id="pinscount"><%=Pin.count%></p>
<div class="footer footer-main">
	<div class="container">
		<div style="" class="footer_teaser">
			<p>David Bedussa <br/>
				Tel Aviv,<br/>
				Israel
			</p>
			<p><i class="fa fa-envelope"></i> Davidbedussa@gmail.com</p>
			<div class="social_wrapper"><a href="https://www.facebook.com/Davidbedussa"><i class="fa fa-facebook"></i></a> <a href="http://www.twitter.com/baddy11"><i class="fa fa-twitter"></i></a> <a href="https://www.linkedin.com/profile/view?id=270327217&trk=nav_responsive_tab_profile"><i class="fa fa-linkedin"></i></a></div>
		</div>
		<p class="counter-heading black" style="color:black;">Number of wishes</p>
		<div class="counter-wrapper">
		  <ul class="flip-counter default" id="c1"></ul>
		</div>
		<!-- <div class=footer-counter>
		<%- (0..3).to_a.each do |index|%>
		 <%= image_tag("#{digits_array[3-index].to_i}.jpg", :style => "width:35px;border:4px solid #eee")%>
		 <% end%>
		</div> -->
	</div>
</div>
<script>
	(function(i, s, o, g, r, a, m) {
		i['GoogleAnalyticsObject'] = r;
		i[r] = i[r] ||
		function() {
			(i[r].q = i[r].q || []).push(arguments)
		}, i[r].l = 1 * new Date();
		a = s.createElement(o), m = s.getElementsByTagName(o)[0];
		a.async = 1;
		a.src = g;
		m.parentNode.insertBefore(a, m)
	})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

	ga('create', 'UA-54360840-1', 'iam21.today');
	ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css">
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "David B +21", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if user_signed_in? && current_user.pins.count == 0 %>
   	 	<span class="navbar-brand" style="font-size:large;color:#000;margin-left:60px;">Always remember, Never Forget 9/11</span>
    <%else%>
    	<span class="navbar-brand" style="font-size:large;color:#000;margin-left:290px;">Always remember, Never Forget 9/11</span>
    <%end%>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"></span> Home
            <% end %></li>
        <li><%= link_to about_path do %>
              <span class="glyphicon glyphicon-star"></span> About
            <% end %></li>
        <% if user_signed_in? %>
          <li>
          	<% if current_user.pins.count == 0 %>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-gift"></span> Wish happy birthday
            <% end %>
        <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-cog"></span> Account Setting
            <% end %>
            </li>
          
          <li><%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Log out
            <% end %></li>
        <% else %>
          <li><%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-user"></span> Sign in
            <% end %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>David B +21</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %><%= stylesheet_link_tag    "social-buttons-3", media: "all", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/_facebook_connect.html.erb
<%= link_to user_omniauth_authorize_path("facebook") do %>
<button class="facebook_button new_button">
	FACEBOOK
	<br>
	CONNECT
</button>
<%end%>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<div class="row">
		<div class="col-xs-3" style="margin-right: -1px;margin-left: 70px;">
			<%= image_tag("davidB.jpg" , :style => "height:150px;width:150px;")%>
		</div>
		<div class="col-xs-6" style="margin-left: -65px;">
			<h1 style="font-size:30px !important;">Hi! Today I'm 21! Its my Birthday!
			<br/>
			So cool,right?</h1>
		</div>
		<div class="col-xs-3" style="margin-left: -95px;">
			<% if user_signed_in? %>
			<div>
				<p>
					<%if current_user.pins.count > 0 %>
					<h1 style="font-size:70px !important;color: #3498db;">+21</h1>
					<% else %>
					<%= link_to "+21",new_pin_path, class:"plus21" %>
					<%end %>
				</p>
			</div>
			<%else %>

			<div id="happyBdayplus21">
				<%= link_to "+21","#", class:"plus21"%>
			</div>
			<%end%>

		</div>
	</div>

	<% if user_signed_in? %>
	<div>
		<p>
			<%if current_user.pins.count > 0 %>
			<h2 style="font-size:30px;color:#099; !important;">Thanks for your wishes! :)</h2>
			<% else %>
			<%= link_to new_pin_path do %>
			<button class="login_button new_button" style="width:230px;">
				Say Happy Birthday ;-) <i class="glyphicon glyphicon-pencil"></i>
			</button>
			<%end%>
			<%end %>
		</p>
	</div>
	<%else %>

	<div id="happyBdayBtn">

		<p>
			<%= link_to "#" do %>
			<button class="login_button new_button" style="width:230px;">
				Say Happy Birthday ;-) <i class="glyphicon glyphicon-pencil"></i> 
			</button>
			<%end%>
		</p>
	</div>
	<%end%>
	<div id="loginBtns" class="hidden">
		<%= link_to new_user_session_path do %>
		<button class="login_button new_button">
			Login
		</button>
		<%end%>
		<%= link_to new_user_registration_path do %>
		<button class="signup_button new_button">
			Sign up
		</button>
		<%end%>
		<%= link_to user_omniauth_authorize_path("twitter") do %>
		<button class="twitter_button new_button" style="width:240px;">
			<i class="fa fa-twitter"></i> | Connect with Twitter
		</button>
		<%end%>
		<%= link_to user_omniauth_authorize_path("facebook") do %>
		<button class="facebook_button new_button" style="width:250px;">
			<i class="fa fa-facebook"></i> | Connect with Facebook
		</button>
		<%end%>
	</div>

</div>

app/views/pages/_twitter_connect.html.erb
<%= link_to user_omniauth_authorize_path("twitter") do %>
<button class="twitter_button new_button" style="float:right;">
	TWITTER
	<br>
	CONNECT
</button>
<%end%>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>A birthday is one of the most important milestones of a person's year. It's a time to step forward and let your mother, your father, your sister or brother, or your friend or coworker know just how much they mean to you.</p>
<p>These days, Facebook and email make it easy to step forward and tell your loved ones how much you care...but maybe it's too easy. Even if we think of ourselves as thoughtful, caring people, we've all dashed off a "Happy Birthday!" to a near-stranger, out of a sense of digital obligation. It feels tiring to give birthday greetings like that, and even more draining to receive them -- and that's never how a birthday should feel.</p>
<p>We put together this site because we believe that birthdays should be special again. We want technological innovation to serve humanity and bring people together, rather than to place barriers between people and call it intimacy.</p>
<p>Our site asks you to write fifty words (or more) of birthday wishes to your loved one. Maybe that seems like a lot in our bustling digital age where we're used to trying to keep things brief, but we promise it's not. Once you start writing about what your loved one means to you, what you want for them in their lives, what your hopes for the coming year are ... you won't want to stop. You'll rediscover how good it feels to say good things.</p>
<p>We also give you the option of uploading a picture of your choice. It can be anything ranging from a funny picture of a cute animal to a memory of you and your friend together to something profound and inspirational. How you choose to uplift your friends and cheer them up on their special days is up to you.</p>
<p>So check your calendar. Who's birthday is coming up? Who means the most to you, and who do you want to show that you care? Set up an account on our website using Twitter or Facebook, get your friends in on what's happening and help us put meaning back into birthdays. Your friends might turn around in a few months and do the same for you. We promise: you'll never want to dash off another impersonal "Happy Birthday" again.</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
<% if @pin.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@pin.errors.count, "error") %> prohibited this message from being saved :(( </h2>

	<ul>
		<% @pin.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.file_field :image, class: "hidden", :id => "image_file" %>
	<div>
		<button onclick="document.getElementById('image_file').click(); return false;">
			<i  class="fa fa-paperclip fa-4"> Choose File</i>
		</button>
		<%= f.label "Choose a picture of us, or choose whatever you want, but should be cool ;-)", :for => "image_file", style: "margin-left: 10px"%>
	</div>
</div>

<div class="form-group">
	<%= f.label "Message"%>
	<%= f.text_area :description, class: "form-control", style: "width:700px; height:250px;", :placeholder => "Please write here your birthday's message.....", :id => "new_pin_description" %>
	<div id="counter_text">
		Dont be lazy, <span id="display_count", style='color:red;'>50</span> more words please to make it a cool message :)
	</div>
</div>

<div class="form-group">
	<%= f.submit "Send the message", class: "btn btn-primary" %>
</div>
<% end %>

<script>
	$(document).ready(function() {
		$("#new_pin_description").on('keyup', function() {
			var words = this.value.length;

			if (words < 50) {
				$('#display_count').text(50 - words);
				$('#counter_text').removeClass("hidden");
			} else {
				$('#counter_text').addClass("hidden");
			}
		});
	}); 
</script>

app/views/pins/_list.html.erb
<
<div id="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>
		<div class="box panel panel-default pindiv" id="pindiv_<%=pin.id%>" data-id="<%=pin.id%>">
			<%= render 'pin', :pin => pin %>
		</div>
	<% end %>
</div>

app/views/pins/_pin.html.erb
<%= link_to image_tag(pin.image.url(:medium)), pin %>

<div class="panel-body">
	
	<div style="float:right">
		<span style="color:#3498db; !important;"> <% if pin.likes.count > 0 %><%= image_tag("smallblueheart.png",:style => "width:20px;height:18px;")%><%= pin.likes.count %><%end%></span>
	</div>
	<div class="col-xs-6">
		<img class="img-responsive img-circle avatar-img" src=<%= pin.user.profile_pic_url%> />
	</div>
	<br/><br/>

	<%= pin.description %>
	<br/>
	<div style="float: right">
		<% if user_signed_in? && pin.user != current_user %>
		<% if pin.likes.where(user_id: current_user.id).blank? %>
		<%= link_to "Like",  id: "like_pin_#{pin.id}", data: {pin_id: pin.id}, class: "like_pin" do %>
		<%= image_tag("like-button3d.jpg", :style => "width:40px;")%>
		<%end%>
		<% else %>
		<%= link_to "Unlike",  id: "unlike_pin_#{pin.id}",data: {pin_id: pin.id,like_id: pin.likes.where(user_id: current_user.id).first.id}, class: "unlike_pin" do %>
		<%= image_tag("ilikeit.jpg", :style => "width:40px;")%>
		<%end%>
		<% end %>
		<% end %>
	</div>
	<p>
		<%- if pin.user%>
		<%- if pin.user.name.present?%>
		<strong><%= pin.user.name %></strong>
		<br/>
		<% end %>
		<%- if pin.user.email_verified?%>
		<strong><%= pin.user.email %></strong>
		<br/>
		<% end %>
		<%- if pin.user.twitter_handle%>
		<strong><%= pin.user.twitter_handle_display %></strong>
		<% end%>
		<% end %>
	</p>

	<% if pin.user == current_user %>
	<div class="actions">
		<%= link_to 'Edit', edit_pin_path(pin) %>
		<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
	<% end %>
	<div id="shareBtns<%= pin.id%>" class="hidden">
		<%= link_to "https://www.facebook.com/dialog/feed?app_id=323761284454080&display=popup&caption=#{pin.description}&link=#{request.protocol}#{request.host_with_port}#{pin_path(pin)}&redirect_uri=#{request.protocol}#{request.host_with_port}&picture=#{pin.image.url(:medium)}" do %>
		<button class="facebook_button new_button" style="width:72px;height:30px;padding:10px;">
			<i class="fa fa-facebook"></i> | Share
		</button>
		<%end%>
		<%= link_to "https://twitter.com/intent/tweet?text=#{pin.description} %23iam21today,Chk it out on #{request.protocol}#{request.host_with_port}#{pin_path(pin)}" do %>
		<button class="twitter_button new_button" style="width:78px;height:30px;padding:10px;">
			<i class="fa fa-twitter"></i> | Share
		</button>
	</div>
	<%end%>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
 
<%= render 'list', :pins => @pins %>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div> 

app/views/pins/new.html.erb
 <div class="form-group" >

<h2>New Birthday's Message</h2>

<%= render 'form'  %>
<%= render 'list', :pins => @pins %>
<%= link_to 'Back', pins_path  %>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p>
					<%= @pin.description %>
				</p>
				<p>
					<%- if @pin.user%>
					<%- if @pin.user.name.present?%>
					<strong><%= @pin.user.name %></strong>
					<br/>
					<% end %>
					<%- if @pin.user.email_verified?%>
					<strong><%= @pin.user.email %></strong>
					<br/>
					<% end %>
					<%- if @pin.user.twitter_handle%>
					<strong><%= @pin.user.twitter_handle_display %></strong>
					<% end%>
					<% end %>
				</p>

				<% if @pin.user == current_user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %>
				<% end %>
				<%= link_to "https://www.facebook.com/dialog/feed?app_id=323761284454080&display=popup&caption=#{@pin.description}&link=#{request.protocol}#{request.host_with_port}#{pin_path(@pin)}&redirect_uri=#{request.protocol}#{request.host_with_port}&picture=#{@pin.image.url(:medium)}" do %>
				<button class="facebook_button new_button" style="width:72px;height:30px;padding:10px;">
					<i class="fa fa-facebook"></i> | Share
				</button>
				<%end%>
				<%= link_to "https://twitter.com/intent/tweet?text=#{@pin.description} %23iam21today,Chk it out on #{request.protocol}#{request.host_with_port}#{pin_path(@pin)}" do %>
				<button class="twitter_button new_button" style="width:78px;height:30px;padding:10px;">
					<i class="fa fa-twitter"></i> | Share
				</button>
				<%end%>
			</div>
		</div>
	</div>
</div>